services:
  cafe_fronted:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_TURNSTILE_SITE_KEY=${VITE_TURNSTILE_SITE_KEY}
    expose:
      - "80"
    restart: unless-stopped
